#!/usr/bin/env bash
# =============================================================================
# persist-vlans.sh
# Makes VLAN subinterfaces and iptables rules persistent across reboots
# using netplan (Ubuntu 22.04) and iptables-persistent.
#
# Usage: sudo bash persist-vlans.sh
# =============================================================================
 
set -euo pipefail
 
PARENT_IFACE="wlp2s0"
NETPLAN_FILE="/etc/netplan/99-lab-vlans.yaml"
IPTABLES_FILE="/etc/iptables/rules.v4"
 
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }
 
[[ $EUID -ne 0 ]] && err "Run as root: sudo bash $0"
 
# ── Step 1: Write netplan VLAN config ─────────────────────────────────────────
log "Writing netplan VLAN configuration to $NETPLAN_FILE..."
cat > "$NETPLAN_FILE" << EOF
# Lab VLAN subinterfaces — generated by persist-vlans.sh
# EDIT: Replace $PARENT_IFACE with your wireless interface name if different
network:
  version: 2
  vlans:
    ${PARENT_IFACE}.10:
      id: 10
      link: ${PARENT_IFACE}
      addresses: [10.10.10.1/24]
 
    ${PARENT_IFACE}.15:
      id: 15
      link: ${PARENT_IFACE}
      addresses: [10.10.15.1/24]
 
    ${PARENT_IFACE}.20:
      id: 20
      link: ${PARENT_IFACE}
      addresses: [10.10.20.1/24]
EOF
 
chmod 600 "$NETPLAN_FILE"
log "Netplan file written ✓"
 
# ── Step 2: Test netplan config before applying ───────────────────────────────
log "Testing netplan configuration..."
netplan generate 2>&1 || err "Netplan config invalid — check $NETPLAN_FILE"
log "Netplan config valid ✓"
 
# ── Step 3: Apply netplan ─────────────────────────────────────────────────────
warn "Applying netplan — this may briefly interrupt network connectivity..."
netplan apply
log "Netplan applied ✓"
 
# ── Step 4: Enable IP forwarding permanently ──────────────────────────────────
log "Enabling IP forwarding permanently..."
if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
  echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi
sysctl -p > /dev/null
log "IP forwarding persistent ✓"
 
# ── Step 5: Persist iptables rules ────────────────────────────────────────────
log "Installing iptables-persistent..."
DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent > /dev/null 2>&1
 
log "Saving current iptables rules..."
mkdir -p /etc/iptables
iptables-save > "$IPTABLES_FILE"
log "iptables rules saved to $IPTABLES_FILE ✓"
 
# ── Step 6: Persist 8021q module load ────────────────────────────────────────
log "Ensuring 8021q module loads on boot..."
if ! grep -q "8021q" /etc/modules; then
  echo "8021q" >> /etc/modules
fi
log "8021q added to /etc/modules ✓"
 
# ── Verify ────────────────────────────────────────────────────────────────────
echo ""
log "=== Persistence Summary ==="
echo "  Netplan config:    $NETPLAN_FILE"
echo "  iptables rules:    $IPTABLES_FILE"
echo "  sysctl:            net.ipv4.ip_forward=1 in /etc/sysctl.conf"
echo "  kernel modules:    8021q in /etc/modules"
echo ""
log "VLANs and firewall rules will survive reboots."
warn "WireGuard (wg0): enable with: sudo systemctl enable wg-quick@wg0"
warn "Suricata:        already enabled via: sudo systemctl enable suricata"
